# Environment
env=qa
base.url=https://reqres.in/api/
api.key=reqres_6a55fcc85e5c43ea80cc04fa74753b6e
content.type=application/json
page.number=2
expected.status.code=200
expected.page=2
user.id=2
update.name=Marilyn
update.job=Actor